In [6]:
import tensorflow as tf


In [7]:
!tf_upgrade_v2 --infile upgraded.py --outfile upgraded1.py

TensorFlow 2.0 Upgrade Script
-----------------------------
Converted 1 files
Detected 0 issues that require attention
--------------------------------------------------------------------------------


Make sure to read the detailed log 'report.txt'



In [9]:
from tensorflow.keras.layers import Input

In [1]:
import numpy as np

In [3]:
a = np.array([[[1, 2], [3, 4]]])
b = np.array([[[5, 6],[3, 4]]])
np.concatenate((a, b), axis=1)

array([[[1, 2],
        [3, 4],
        [5, 6],
        [3, 4]]])

In [21]:
a=np.random.rand(3,3,3,3)
print(a)

[[[[0.56975756 0.56205785 0.88019366]
   [0.03068448 0.02083929 0.42219065]
   [0.48777007 0.32942729 0.57598394]]

  [[0.66910058 0.64961125 0.47859145]
   [0.24979513 0.72604159 0.59007467]
   [0.46782077 0.02006119 0.92539135]]

  [[0.59331127 0.06065077 0.61886029]
   [0.14768681 0.7666539  0.01465685]
   [0.52856466 0.73432217 0.84592043]]]


 [[[0.19477203 0.45257862 0.47040687]
   [0.98403626 0.65135585 0.26231221]
   [0.29635162 0.71217625 0.83938477]]

  [[0.36961333 0.03906665 0.84599467]
   [0.46817287 0.92766021 0.27930374]
   [0.84203131 0.35793346 0.82953566]]

  [[0.63967729 0.94475324 0.83332239]
   [0.47703897 0.19859584 0.37461834]
   [0.49548603 0.75473916 0.07353521]]]


 [[[0.85230556 0.34276522 0.75428944]
   [0.27387494 0.3987846  0.0213952 ]
   [0.53404943 0.18148446 0.49697986]]

  [[0.39012028 0.49747569 0.84700099]
   [0.77849513 0.04474101 0.8474149 ]
   [0.74919949 0.11204401 0.92596515]]

  [[0.63415428 0.96651726 0.48369896]
   [0.67768416 0.29927544 0.06

In [22]:
b=np.random.rand(3,3,3,3)
print(b)

[[[[0.91649828 0.17487013 0.86216849]
   [0.06569402 0.93313531 0.78391612]
   [0.27735839 0.65180729 0.11865655]]

  [[0.79007994 0.35892824 0.93537482]
   [0.04217327 0.24960473 0.60206561]
   [0.74016152 0.90738518 0.35555784]]

  [[0.91234849 0.07462807 0.04187945]
   [0.08207138 0.38485564 0.35473413]
   [0.84824414 0.84404633 0.28253615]]]


 [[[0.71752053 0.21507838 0.12000422]
   [0.79582279 0.92448622 0.28559895]
   [0.78008587 0.11162659 0.821024  ]]

  [[0.94434409 0.40136592 0.21745908]
   [0.89491857 0.49155425 0.16432976]
   [0.07774215 0.51606626 0.89675103]]

  [[0.04916315 0.0793492  0.97827807]
   [0.21985446 0.17447691 0.66531373]
   [0.48415457 0.22793654 0.11350275]]]


 [[[0.79212565 0.94190269 0.29568375]
   [0.87567636 0.84858033 0.94199198]
   [0.06548347 0.6138798  0.04887764]]

  [[0.04621908 0.11516422 0.91182967]
   [0.85968044 0.28202727 0.70789738]
   [0.18975915 0.42664705 0.41730359]]

  [[0.29268965 0.97346076 0.0938847 ]
   [0.14268646 0.39710663 0.42

In [23]:
np.concatenate((a, b), axis=3)

array([[[[0.56975756, 0.56205785, 0.88019366, 0.91649828, 0.17487013,
          0.86216849],
         [0.03068448, 0.02083929, 0.42219065, 0.06569402, 0.93313531,
          0.78391612],
         [0.48777007, 0.32942729, 0.57598394, 0.27735839, 0.65180729,
          0.11865655]],

        [[0.66910058, 0.64961125, 0.47859145, 0.79007994, 0.35892824,
          0.93537482],
         [0.24979513, 0.72604159, 0.59007467, 0.04217327, 0.24960473,
          0.60206561],
         [0.46782077, 0.02006119, 0.92539135, 0.74016152, 0.90738518,
          0.35555784]],

        [[0.59331127, 0.06065077, 0.61886029, 0.91234849, 0.07462807,
          0.04187945],
         [0.14768681, 0.7666539 , 0.01465685, 0.08207138, 0.38485564,
          0.35473413],
         [0.52856466, 0.73432217, 0.84592043, 0.84824414, 0.84404633,
          0.28253615]]],


       [[[0.19477203, 0.45257862, 0.47040687, 0.71752053, 0.21507838,
          0.12000422],
         [0.98403626, 0.65135585, 0.26231221, 0.79582279, 0.92